export enum BlockchainType {
  ETHEREUM = 'ETHEREUM',
  BSC = 'BSC',
  POLYGON = 'POLYGON',
  AVALANCHE = 'AVALANCHE',
  BASE = 'BASE',
  ARBITRUMONE = 'ARBITRUMONE',
  BLAST = 'BLAST',
  OPTIMISM = 'OPTIMISM',
}
